//! Paths to deterministic fixtures shared by crate unit tests.

use std::path::PathBuf;

/// Returns the path to a synthetic RPA-3.0 archive for testing.
///
/// The checked-in file is regenerated by `tests/build_fixtures.py` in CI.
pub fn rpa_v3_fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/sample.rpa")
}
